apiVersion: v1
kind: Namespace
metadata:
  name: java

---
# 1. The Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-app
  namespace: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-app
  template:
    metadata:
      labels:
        app: secure-app
    spec:
      containers:
      - name: app
        # WE WILL REPLACE THIS IMAGE TAG DYNAMICALLY IN JENKINS
        image: HARBOR_REGISTRY_PLACEHOLDER/library/secure-app:TAG_PLACEHOLDER
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"

---
# 2. The Internal Service
apiVersion: v1
kind: Service
metadata:
  name: secure-app-svc
  namespace: java
spec:
  selector:
    app: secure-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
# 3. The Public Ingress (URL)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secure-app-ingress
  namespace: java
  annotations:
    # Use 'nginx' if using Nginx Ingress, or your specific class
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /secure-app
        pathType: Prefix
        backend:
          service:
            name: secure-app-svc
            port:
              number: 80